name: Dependabot

on:
  pull_request_target:

jobs:
  dependabot:
    name: Merge PR
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Load Dependabot meta-data
        uses: dependabot/fetch-metadata@v2.1.0
        id: dependabot-metadata
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge minor/patch updates
        run: gh pr merge "${{ github.event.pull_request.html_url }}" --merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: >
          steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major'